site_name: myzone
nav:
- 'Home':
    - 'About': 'home/index.md'
- 'AWS':
    - 'CLI': 'aws/cli.md'
    - 'Learning': 'aws/learning.md'
    - 'Elastic Container Service (ECS)': 'aws/ecs.md'
    - 'Tools': 'aws/tools.md'
- 'kubernetes':
    - 'Commands': 'kubernetes/commands.md'
    - 'References': 'kubernetes/references.md'
    - 'Tools': 'kubernetes/tools.md'
- 'Linux':
    - 'Commands': 'linux/commands.md'
- 'iTerm2':
    - 'Cheatsheet': 'iterm2/cheatsheet.md'
- 'Mkdocs':
    - 'How to use Mkdocs': 'mkdocs/contribute.md'
    - 'Markdown Syntax': "mkdocs/markdown.md"
- 'Tools':
    - 'iTerm2': 'tools/iterm2.md'
    - 'Brew': 'tools/brew.md'
    - 'Grafana': 'tools/grafana.md'
    - 'Prometheus': 'tools/prometheus.md'
- 'Tutorials':
    - 'Linux Server Admin': 'videos/video.md'


#Theme options
theme:
  name: material
  logo: 'assets/24i Logo HQ Hex Crimson.png'
  favicon: 'assets/24i_favicon.png'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: indigo

#Plugins
      plugins:
         - mkdocs-video

#Footers
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/24i
    - icon: fontawesome/brands/slack
      link: https://amino24i.slack.com/archives/C03H7V6CDEY
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/24i_Media
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/24i/mycompany/verification/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
   
copyright: |
  &copy; 2023 <a href="https://github.com/24i"  target="_blank" rel="noopener">24i CloudOps</a>